# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.22)
{
  description = "The host flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
    flake-checker.url = "github:DeterminateSystems/flake-checker";
    flake-iter.url = "github:DeterminateSystems/flake-iter";
  };

  outputs = { self, nixpkgs, flake-iter, flake-checker }:
    let
      
      supportedSystems = [ "x86_64-linux" "aarch64-darwin" "x86_64-darwin" "aarch64-linux" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    in {
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          packages = with pkgs; [
            nixpkgs-fmt
            flake-iter.packages.${system}.default
            flake-checker.packages.${system}.default
          ];
        };
      });
      templates = {
        default = {
          description = "a template";
          path = ./templates/default;
          welcomeText = ''
            Welcome to the default template
          '';
        };
      };
    };
}
